### ISSUE TITLE
Pulling down old Teevity/ice version

### ISSUE THREAD

**Issue by screechdiesel** [jonbrouse/docker-ice#21]
Hello. Recently noticed that docker builds are pulling down old java code  

Dockerfile:
FROM jonbrouse/ice:latest
....

Results in
-rw-rw-r--. 202 root root 5988 Feb 22  2016 /opt/ice/src/java/com/netflix/ice/tag/Zone.java

Which is a couple versions old and results in runtime errors.  

Pulling down https://github.com/Teevity/ice/archive/v1.0.tar.gz instead of 
https://github.com/Teevity/ice/archive/v1.1.tar.gz?

Thanks for any information!

**Comment by jhaohai** [comment]
update to 1.1 please, this is the latest version
[https://github.com/Teevity/ice/releases/tag/v1.1](https://github.com/Teevity/ice/releases/tag/v1.1)

**Comment by jonbrouse** [comment]
The build job wasn't updating the ICE version in the Dockerfile on master. This has since been resolved and any new release tags in the Teevity repo will trigger a Travis CI job that will update tie Dockerfile on master in this repo with the new version and create a new release tag. The Docker Hub will pick up the new tag and build a new image.
